import {type Subscription} from '../../models/subscription/subscription.model';

export const SUBSCRIPTION_MOCK_DATA: Subscription[] = [
  {
    id: 's1',
    name: 'Netflix',
    category: 'Entertainment',
    amount: 15.99,
    frequency: 'monthly',
    nextDate: '2026-05-21',
    status: 'active',
    logo: 'N',
    color: '#e50914',
  },
  {
    id: 's2',
    name: 'Equinox Gym',
    category: 'Health',
    amount: 55.0,
    frequency: 'monthly',
    nextDate: '2026-05-15',
    status: 'active',
    logo: 'E',
    color: '#1a1a1a',
  },
  {
    id: 's3',
    name: 'Apple iCloud',
    category: 'Storage',
    amount: 2.99,
    frequency: 'monthly',
    nextDate: '2026-05-08',
    status: 'active',
    logo: 'A',
    color: '#555555',
  },
  {
    id: 's4',
    name: 'Con Edison',
    category: 'Utilities',
    amount: 142.0,
    frequency: 'monthly',
    nextDate: '2026-05-18',
    status: 'active',
    logo: 'C',
    color: '#003087',
  },
  {
    id: 's5',
    name: 'Spotify',
    category: 'Entertainment',
    amount: 9.99,
    frequency: 'monthly',
    nextDate: '2026-05-03',
    status: 'active',
    logo: 'S',
    color: '#1db954',
  },
  {
    id: 's6',
    name: 'Adobe CC',
    category: 'Software',
    amount: 54.99,
    frequency: 'monthly',
    nextDate: '2026-05-12',
    status: 'active',
    logo: 'A',
    color: '#ff0000',
  },
  {
    id: 's7',
    name: 'Amazon Prime',
    category: 'Shopping',
    amount: 14.99,
    frequency: 'monthly',
    nextDate: '2026-05-22',
    status: 'active',
    logo: 'a',
    color: '#ff9900',
  },
  {
    id: 's8',
    name: 'NY Times',
    category: 'Media',
    amount: 4.0,
    frequency: 'monthly',
    nextDate: '2026-06-01',
    status: 'paused',
    logo: 'T',
    color: '#333333',
  },
];
