// <auto-generated />
using System;
using FinanceSentry.Modules.Research.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSentry.Modules.Research.Migrations
{
    [DbContext(typeof(ResearchDbContext))]
    [Migration("20260708112134_M006_OpportunityCandidates")]
    partial class M006_OpportunityCandidates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("research")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.CandidateScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CandidateId")
                        .HasColumnType("uuid");

                    b.Property<string>("CrowdingClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("FormulaVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("FundamentalsScore")
                        .HasColumnType("integer");

                    b.Property<string>("IpsFit")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ScoredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("StructureScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CandidateId", "ScoredAt")
                        .HasDatabaseName("idx_candidate_scores_candidate_scored");

                    b.ToTable("candidate_scores", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.InvestmentPolicyStatement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AllocationTargets")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContributionPlan")
                        .HasColumnType("jsonb");

                    b.Property<int>("CoolingOffDays")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("EmergencyCushionUsd")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Goals")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("MaxDrawdownTolerancePct")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("MaxSinglePositionPct")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("PrimaryHorizonYears")
                        .HasColumnType("integer");

                    b.Property<string>("RebalancingRule")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ReviewCadence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("RiskCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("RiskTolerance")
                        .HasColumnType("integer");

                    b.Property<string>("SellDiscipline")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsCurrent")
                        .HasDatabaseName("idx_ips_user_current");

                    b.HasIndex("UserId", "Version")
                        .IsUnique()
                        .HasDatabaseName("idx_ips_user_version");

                    b.ToTable("investment_policy_statements", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.InvestmentThesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset?>("BrokenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BrokenReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Catalysts")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("InvalidationTriggers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("KeyDataPoints")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ThesisText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Ticker")
                        .HasDatabaseName("idx_thesis_user_ticker");

                    b.ToTable("theses", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.MacroEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EventTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventDate")
                        .HasDatabaseName("idx_macro_date");

                    b.HasIndex("EventDate", "Region", "Event")
                        .IsUnique()
                        .HasDatabaseName("idx_macro_dedup");

                    b.ToTable("macro_events", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("IngestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Summary")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Tickers")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("idx_news_hash");

                    b.HasIndex("PublishedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_news_published");

                    b.ToTable("news_articles", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.OpportunityCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NominationReasons")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("PromotedThesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_opportunity_candidates_user_status");

                    b.HasIndex("UserId", "Ticker")
                        .HasDatabaseName("idx_opportunity_candidates_user_ticker");

                    b.ToTable("opportunity_candidates", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.QuoteCacheEntry", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasDefaultValue("USD");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("PreviousClose")
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Ticker");

                    b.ToTable("quote_cache", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.ThesisEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("BenchmarkPrice")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("BenchmarkTicker")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("SPY");

                    b.Property<string>("DecisionNote")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("PricesPending")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SubjectPrice")
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PricesPending")
                        .HasDatabaseName("idx_thesis_events_pending");

                    b.HasIndex("SubjectType", "SubjectId", "Timestamp")
                        .HasDatabaseName("idx_thesis_events_subject");

                    b.HasIndex("UserId", "EventType", "Timestamp")
                        .HasDatabaseName("idx_thesis_events_user_type_time");

                    b.ToTable("thesis_events", "research");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Research.Domain.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Ticker")
                        .IsUnique()
                        .HasDatabaseName("idx_watchlist_user_ticker");

                    b.ToTable("watchlist_items", "research");
                });
#pragma warning restore 612, 618
        }
    }
}
