// <auto-generated />
using System;
using FinanceSentry.Modules.Risk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinanceSentry.Modules.Risk.Migrations
{
    [DbContext(typeof(RiskDbContext))]
    partial class RiskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("risk")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinanceSentry.Modules.Risk.Domain.HoldingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(24,8)");

                    b.Property<string>("Sleeve")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("UsdValue")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Symbol", "Sleeve", "CapturedAt")
                        .HasDatabaseName("idx_holding_snapshots_identity");

                    b.ToTable("holding_snapshots", "risk");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Risk.Domain.PolicyViolationAck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ObservedAtAck")
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("RemediationNote")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WorseningStepPct")
                        .HasColumnType("numeric(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RuleKey", "Subject", "IsActive")
                        .HasDatabaseName("idx_policy_violation_acks_identity");

                    b.ToTable("policy_violation_acks", "risk");
                });

            modelBuilder.Entity("FinanceSentry.Modules.Risk.Domain.RiskRuleSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AllocationTargets")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("allocation_targets_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxLossPerThesisPct")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("MaxNewPositionPct")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("MaxPositionWeightPct")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("MaxSleeveWeightPct")
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("MinCashBufferPct")
                        .HasColumnType("numeric(9,6)");

                    b.Property<int?>("TurnoverBudgetPerQuarter")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsCurrent")
                        .HasDatabaseName("idx_risk_rule_sets_user_current");

                    b.ToTable("risk_rule_sets", "risk");
                });
#pragma warning restore 612, 618
        }
    }
}
