export enum AppRoute {
  Root = '/',
  Login = '/login',
  Register = '/register',
  McpConnect = '/mcp/connect',
  Accounts = '/accounts',
  AccountsList = '/accounts/list',
  AccountsInvestments = '/accounts/investments',
  Dashboard = '/dashboard',
  Transactions = '/transactions',
  Investments = '/investments',
  Budgets = '/budgets',
  Subscriptions = '/subscriptions',
  Alerts = '/alerts',
  Settings = '/settings',
}
